---

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

#linter:
  #image: hadolint/hadolint:latest-debian
  #script:
    #- hadolint --version
    #- hadolint *.Dockerfile

.build:
  image: docker
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE"
        -t "$CI_REGISTRY_IMAGE:$CI_JOB_NAME" - < "./$CI_JOB_NAME.Dockerfile"
    - docker run  "$CI_REGISTRY_IMAGE:$CI_JOB_NAME" sh -x -c '
        make --version;
        gcc --version;
        arm-none-eabi-gcc --version;
        clang --version;
        git --version;
        rsync --version;
        true '
    - docker push "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
  script:
    - echo done

alpine:
  extends: .build

intel:
  tags:
    - perun
  extends: .build

archlinux:
  extends: .build
  script:
    - docker tag "$CI_REGISTRY_IMAGE:$CI_JOB_NAME" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

ubuntu:
  extends: .build
