---

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

hadolint:
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint --version
    - hadolint *.Dockerfile
  allow_failure: true

.build:
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build
        -t "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
        -f "./$CI_JOB_NAME.Dockerfile" .
    - docker run "$CI_REGISTRY_IMAGE:$CI_JOB_NAME" sh -s <test.sh
    - docker push "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
  script:
    - echo done

alpine:
  extends: .build

intel:
  extends: .build

archlinux:
  extends: .build
  script:
    - docker tag "$CI_REGISTRY_IMAGE:$CI_JOB_NAME" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

ubuntu:
  extends: .build
