on:
  - push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine
          - intel
          - archlinux
          - ubuntu
    runs-on: nomadtools mem=1000
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      # - uses: hadolint/hadolint-action@v3.1.0
      #   with:
      #     dockerfile: ./${{matrix.image}}.Dockerfile
      - run: echo "TAG=ghcr.io/${GITHUB_REPOSITORY,,}:${{matrix.image}}" >>${GITHUB_ENV}
      - run: docker build --pull -f ./${{matrix.image}}.Dockerfile -t $TAG .
      - run: docker run $TAG sh -s <test.sh
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: docker push $TAG
