on:
  - push
jobs:
  build:
    strategy:
      matrix:
        image:
          - alpine
          - intel
          - archlinux
          - ubuntu
    runs-on: nomadtools
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./${{matrix.image}}.Dockerfile
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v3
        with:
          file: ./${{matrix.image}}.Dockerfile
          pull: true
          tags: ghcr.io/${{ github.repository }}:${{matrix.image}}
